apiVersion: v1
kind: ConfigMap
metadata:
  name: indico-config
  namespace: indico
data:
  PGHOST: indico-postgres
  PGDATABASE: indico
  PGPORT: "5432"
  POSTGRES_HOST: indico-postgres
  POSTGRES_DB: indico
  REDIS_CACHE_URL: redis://indico-redis:6379/1
  REDIS_HOST: indico-redis
  CELERY_BROKER: redis://indico-redis:6379/0
  SERVICE_HOSTNAME: indico.ai4energy.cn
  SERVICE_PORT: "80"
  SERVICE_PROTOCOL: http
  # 初次启动时使用以下配置，启动成功后注释掉以下三行
  #SERVICE_HOSTNAME: indico-web
  #SERVICE_PORT: "59999"
  #SERVICE_PROTOCOL: http
  # http启动成功后，改为https，使用以下配置
  #SERVICE_HOSTNAME: indico.ai4energy.cn
  #SERVICE_PORT: "443"
  #SERVICE_PROTOCOL: https
  USE_PROXY: "true"
  INDICO_DEFAULT_TIMEZONE: Asia/Shanghai
  INDICO_DEFAULT_LOCALE: en_US
  INDICO_ROUTE_OLD_URLS: ""
  INDICO_CHECKIN_APP_CLIENT_ID: ""
  INDICO_CUSTOMIZATION_DIR: ""
  INDICO_CUSTOMIZATION_DEBUG: ""
  INDICO_LOGO_URL: ""
  INDICO_STORAGE_DICT: '{"default": "fs:/opt/indico/archive"}'
  INDICO_AUTH_PROVIDERS: "{}"
  INDICO_IDENTITY_PROVIDERS: "{}"
  INDICO_LOCAL_IDENTITIES: "yes"
  SECRET_KEY: pleasereplacemewithsomethingrandom
  C_FORCE_ROOT: "true"
  USE_EXTERNAL_DB: ""
  SMTP_SERVER: ""
  SMTP_PORT: ""
  SMTP_LOGIN: ""
  SMTP_PASSWORD: ""
  SMTP_USE_TLS: ""
