apiVersion: apps/v1
kind: Deployment
metadata:
  name: indico-web
  namespace: indico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indico-web
  template:
    metadata:
      labels:
        app: indico-web
    spec:
      containers:
      - name: indico-web
        image: indico-worker:3.3.3
        command: ["/opt/indico/run_indico.sh"]
        ports:
        - containerPort: 59999
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: indico-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: indico-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: indico-web-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: indico-web-secret
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: indico-config
              key: REDIS_HOST
        volumeMounts:
        - mountPath: /opt/indico/archive
          name: archive-volume
        - mountPath: /opt/indico/log
          name: log-volume
        - mountPath: /opt/indico/custom
          name: custom-volume
        - mountPath: /opt/indico/static
          name: static-volume
      volumes:
      - name: archive-volume
        hostPath:
          path: /srv/indico/archive
      - name: log-volume
        hostPath:
          path: /srv/indico/log
      - name: custom-volume
        hostPath:
          path: /srv/indico/custom
      - name: static-volume
        hostPath:
          path: /srv/indico/static
---
apiVersion: v1
kind: Secret
metadata:
  name: indico-web-secret
  namespace: indico
type: Opaque
data:
  POSTGRES_USER: aW5kaWNv # base64 encoded value for "indico"
  POSTGRES_PASSWORD: aW5kaWNvcGFzcw== # base64 encoded value for "indicopass"
---
apiVersion: v1
kind: Service
metadata:
  name: indico-web
  namespace: indico
spec:
  selector:
    app: indico-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 59999
  type: ClusterIP
