apiVersion: apps/v1
kind: Deployment
metadata:
  name: indico-front-nginx
  namespace: indico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indico-front-nginx
  template:
    metadata:
      labels:
        app: indico-front-nginx
    spec:
      containers:
      - name: indico-front-nginx
        image: nginx:1.27.0
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /srv/indico/web/static
          name: static-volume
        - mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
          name: nginx-config
      volumes:
      - name: static-volume
        hostPath:
          path: /srv/indico/web/static
          type: Directory
      - name: nginx-config
        hostPath:
          path: /path/to/nginx.conf
          type: FileOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: indico-front-nginx
  namespace: indico
spec:
  selector:
    app: indico-front-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
