apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: indico-ai4energy-org-ingress-indico
  namespace: indico
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
  - host: indico.ai4energy.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: indico-front-nginx
            port:
              number: 80
  # tls:
  # - hosts:
  #   - indico.ai4energy.org
  #   secretName: indico-ai4energy-org-certificate-secret
