services:

  indico-redis:
    image: redis:7.4.0
    container_name: indico-redis
    volumes:
      - /srv/indico/redis:/data
    restart: unless-stopped

  indico-postgres:
    image: postgres:16.3
    container_name: indico-postgres
    env_file:
      - indico.env
    volumes:
      - /srv/indico/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  indico-web:
    #image: indico-worker:3.3.3
    image: registry.cn-hangzhou.aliyuncs.com/ai4e/indico-worker:3.3.3
    container_name: indico-web
    depends_on:
      - indico-redis
      - indico-postgres
    env_file:
      - indico.env
    volumes:
      - /srv/indico/archive:/opt/indico/archive
      - /srv/indico/custom:/opt/indico/custom
      - /srv/indico/log/nginx:/opt/indico/log/nginx
      - static-files:/opt/indico/static
    tmpfs:
      - /opt/indico/tmp
    command: ["/opt/indico/run_indico.sh"]
    restart: unless-stopped

  indico-celery:
    #image: indico-worker:3.3.3
    image: registry.cn-hangzhou.aliyuncs.com/ai4e/indico-worker:3.3.3
    container_name: indico-celery
    depends_on:
      - indico-redis
      - indico-postgres
    env_file:
      - indico.env
    volumes_from:
      - indico-web
    command: ["/opt/indico/run_celery.sh"]
    restart: unless-stopped

  indico-nginx:
    image: nginx:1.27.0
    container_name: indico-nginx
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=indico.ai4energy.cn
      - LETSENCRYPT_HOST=indico.ai4energy.cn
      - LETSENCRYPT_EMAIL=mingtao@xjtu.edu.cn
    volumes:
      - /srv/indico/nginx.conf.d:/etc/nginx/conf.d
    volumes_from:
      - indico-web

    # 如果不使用nginx-proxy就注释掉上面的environment中的几条，打开下面的2条
    # ports:
    #   - "80:80"
    
    restart: unless-stopped

networks:
  default:
    name: ai4energynetwork
    external: true

volumes:
  static-files:
